[package]
name = "posish"
version = "0.6.2-alpha.0"
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
    "Jakub Konka <kubkon@jakubkonka.com>",
]
description = "Safe Rust bindings to POSIX-ish libc APIs and syscalls"
documentation = "https://docs.rs/posish"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
repository = "https://github.com/bytecodealliance/posish"
edition = "2018"
keywords = ["api", "file", "network"]
categories = ["filesystem", "network-programming", "os::unix-apis"]
exclude = ["/.github"]

[dependencies]
bitflags = "1.2.1"
itoa = "0.4.7"
unsafe-io = "0.6.0"
io-lifetimes = "0.0.0"

[target.'cfg(not(linux_raw))'.dependencies]
cfg-if = "1.0.0"
errno = "0.2.7"
libc = { version = "0.2.87", features = ["extra_traits"] }

[target.'cfg(linux_raw)'.dependencies]
linux-raw-sys = { version = "0.0.0", features = ["v5_4", "v5_11"] }

[dev-dependencies]
atty = "0.2.14"
tempfile = "3.2.0"

[badges]
maintenance = { status = "actively-developed" }
